Fix LinkedIn icon bug #10
ACE-VSIT/acewebsite pull request #12
Opened 2021-05-24 04:44 UTC by nparashar150

**Fixed LinkedIn icon bug**
Replaced it from Font Awesome icon --> custom .svg icon.

**Expected Behavior**
![Screenshot from 2021-05-24 10-10-41](https://user-images.githubusercontent.com/63806451/119297309-513d4780-bc78-11eb-84ec-b10f42b9ff5d.png)

2021-06-05 20:34 UTC, ansh-saini requested changes

2021-06-05 20:34 UTC, ansh-saini commented on users/static/users/css/login.css
> +  }
This breaks the rotate animation on firefox.
Plus, we don't really want the background color to change like that.
Please revert this change.

2021-06-05 20:34 UTC, ansh-saini commented on users/static/users/css/login.css
> +  background: linear-gradient(45deg, rgba(0,119,181,0.2) 0%, rgba(255,102,159,0.2) 100%);
Don't need a gradient here. Please revert this change.

2021-06-05 20:34 UTC, ansh-saini commented on users/static/users/images/Facebook Logo.svg
> +</g>
So many empty `g` elements?

2021-06-05 20:34 UTC, ansh-saini commented on users/static/users/images/Linked Logo.svg
> +<svg width="512" height="512" xmlns="http://www.w3.org/2000/svg">
Rename this file to `Linkedin Logo.svg`

2021-06-05 20:34 UTC, ansh-saini commented on users/static/users/css/login.css
> +  filter: drop-shadow(0 .3rem .3rem #7e0f0083);
This is nice! 🤩

2021-06-05 20:48 UTC, closed without merging

2021-06-06 03:35 UTC, nparashar150 commented on users/static/users/css/login.css
> +  filter: drop-shadow(0 .3rem .3rem #7e0f0083);
Thank You :)

2021-06-06 03:36 UTC, nparashar150 commented on users/static/users/images/Facebook Logo.svg
> +</g>
This was just the avg generated, I didn't made it myself.

2021-06-06 03:42 UTC, nparashar150 commented on users/static/users/css/login.css
> +  background: linear-gradient(45deg, rgba(0,119,181,0.2) 0%, rgba(255,102,159,0.2) 100%);
No worries.