fixed footer position
ACE-VSIT/acewebsite pull request #7
Opened 2021-05-20 14:40 UTC by NikhilSharma03

** Desciption **
The footer was not behaving as it should be.

** Changes **
changes made into main.css file to get the desired output.

2021-05-21 05:09 UTC, ansh-saini commented
Hey @NikhilSharma03. I'll review your PR on the weekend.
I noticed that the formatting of your PR description is not right. Please take a look at [this link](https://www.markdownguide.org/basic-syntax/) to learn more about markdown formatting and how to make your PR look beautiful.
Also, if you want to link your PR to the issue that you solved, you can mention the `#` of the issue in your PR description. The most common practice is to write `Fixes #1` on the top of your PR description. This way you won't have to go the the issue and write a comment asking the maintainers to review your Pull Request.

2021-05-21 07:19 UTC, NikhilSharma03 commented
Ok, thank you. I will keep that in mind next time.

2021-05-22 08:30 UTC, ansh-saini requested changes

2021-05-22 08:30 UTC, ansh-saini commented on website/static/website/css/main.css
> +  height: 100vh; }
If the content is greater than `100vh`, this property will break the scrolling of the content.
Visit `http://localhost:8000/projects/` and try to scroll. The same is happening with mobile devices. Make sure your changes don't break existing functionality and are fully responsive across all screen sizes.

2021-05-24 15:43 UTC, NikhilSharma03 commented
@ansh-saini Can you please review?

2021-06-05 21:10 UTC, merged